# Generated by Django 5.0.3 on 2024-03-31 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0020_alter_game_date_add_alter_infodownload_date_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
