# Generated by Django 5.0.3 on 2024-03-31 02:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_game_date_add_alter_infodownload_date_add'),
        ('pages', '0003_alter_gamead_date_add_alter_gamead_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamead',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 4, 17, 30, 33066)),
        ),
        migrations.AlterField(
            model_name='gamead',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamead', to='games.game'),
        ),
    ]
