# Generated by Django 5.0.3 on 2024-04-06 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_gamead_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamead',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 57, 29, 501256)),
        ),
    ]
