# Generated by Django 5.0.3 on 2024-03-30 20:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='GameImages/%Y/%m/%d/')),
                ('images', models.ImageField(upload_to='GameImages/%Y/%m/%d/')),
                ('game_file', models.FileField(upload_to='Games/%Y/%m/%d/')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2024, 3, 30, 22, 26, 6, 427638))),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
        migrations.CreateModel(
            name='InfoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=datetime.datetime(2024, 3, 30, 22, 26, 6, 427638))),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
