# Generated by Django 5.0.3 on 2024-03-30 21:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_date_add_alter_game_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 23, 16, 41, 492429)),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 23, 16, 41, 492429)),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_info_download', to='games.game'),
        ),
    ]
