# Generated by Django 5.0.3 on 2024-03-30 21:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_date_add_alter_infodownload_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 23, 52, 33, 692994)),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_images', to='games.game'),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 23, 52, 33, 692994)),
        ),
    ]
