# Generated by Django 5.0.3 on 2024-04-06 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_alter_game_date_add_alter_infodownload_date_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['-date_add']},
        ),
        migrations.AddField(
            model_name='gameimage',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 57, 29, 500236)),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 57, 29, 500236)),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 57, 29, 500236)),
        ),
    ]
