# Generated by Django 5.0.3 on 2024-04-06 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_gameimage_options_gameimage_date_add_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={},
        ),
        migrations.AlterField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 59, 0, 861470)),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 59, 0, 862486)),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 59, 0, 862486)),
        ),
    ]
