# Generated by Django 5.0.3 on 2024-04-06 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_alter_gameimage_options_alter_game_date_add_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['-date_add']},
        ),
        migrations.AlterField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 23, 7, 39, 826160)),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 23, 7, 39, 827158)),
        ),
        migrations.AlterField(
            model_name='infodownload',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 23, 7, 39, 827158)),
        ),
    ]
